create table if not exists public."MapInfo" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  latitude double precision not null,
  longtitude double precision not null,
  title text not null,
  description text
);

alter table public."MapInfo" enable row level security;;
