create table if not exists public."GridDensity" (
  id bigint generated by default as identity primary key,
  create_at timestamp with time zone not null default now(),
  latitude double precision not null,
  longtitude double precision not null,
  radius double precision not null,
  even_num integer not null check (even_num >= 3)
);

alter table public."GridDensity" enable row level security;

create index if not exists grid_density_even_num_idx
on public."GridDensity" (even_num desc);;
